Make Amazon scraper work for multiple domains/languages.
jbms/finance-dl pull request #48
Opened 2021-11-13 11:29 UTC by Marvin182

2021-11-13 22:49 UTC, Zburatorul requested changes

2021-11-13 22:49 UTC, Zburatorul commented on finance_dl/amazon.py
> +                    return [a for a in self.driver.find_elements_by_xpath('//a[@class="a-popover-trigger a-declarative"]') if a.text == self.domain.invoice]
@Marvin182, this latest commit now fails on this line (actually on 253).
Your version returns nothing. Dropping the `a.text == ...` part still returns nothing.
Overall it seems the old way of looking for a link with `orderID=` is likely to be more robust to css renamings. 

Also, it seems you forgot to rebase because you've gotten rid of the changes from the latest Amazon Fresh PR.

2021-12-09 20:53 UTC, moritzj29 commented
Hi, I just tested this code with amazon DE and it exported my transactions without errors! Nice! Thanks @Marvin182 ! Are you by any chance also working on an updated amazon importer for beancount-import? So far, the parsing also assumes English HTML files and USD currency...

2022-01-12 12:40 UTC, moritzj29 commented
I addressed the comments in #50

2022-03-11 05:59 UTC, Zburatorul commented
Closing in favor of #50 .

2022-03-11 05:59 UTC, closed without merging